---
title: "video proj"
author: "Yerim Kim (1005861239)"
date: "09/11/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
```

```{r}
video_data <- read.csv("~/Downloads/Video_project_dataset.csv")

##Selecting columns (predictors) that we think are necessary for our dataset
data <- video_data %>% select(NUMBRANCH, CONTROL, REGION, HBCU, PBI, TRIBAL, HSI, WOMENONLY, ADM_RATE, COSTT4_A, AVGFACSAL, PFTFAC, PCTPELL, UG25ABV, INC_PCT_LO, PAR_ED_PCT_1STGEN, FEMALE, MD_FAMINC, PCT_WHITE, PCT_BLACK, PCT_ASIAN, PCT_HISPANIC, PCT_BA, PCT_GRAD_PROF, PCT_BORN_US, POVERTY_RATE, UNEMP_RATE)

##Reordering columns to perform EDA later
colnames(data)
data <- data[,c(9, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27)]
View(data)
```

```{r}
boxplot(ADM_RATE ~ REGION, data = data, col='orange', border='brown', xlab = 'Region Location of Institution')
par(mfrow=c(2,4))
boxplot(ADM_RATE ~ NUMBRANCH, data = data, col='orange', border='brown', xlab = '# of Branch Campuses')
boxplot(ADM_RATE ~ CONTROL, data = data, col='orange', border='brown')
boxplot(ADM_RATE ~ HBCU, data = data, col='orange', border='brown')
boxplot(ADM_RATE ~ PBI, data = data, col='orange', border='brown')
boxplot(ADM_RATE ~ TRIBAL, data = data, col='orange', border='brown')
boxplot(ADM_RATE ~ HSI, data = data, col='orange', border='brown')
boxplot(ADM_RATE ~ WOMENONLY, data = data, col='orange', border='brown')

```

```{r}
par(mfrow=c(1,5))
hist(data$ADM_RATE, main="Admission Rate", xlab="ADM_RATE")
hist(data$NUMBRANCH, main="Number of branch campuses", xlab="NUMBRANCH")
hist(data$CONTROL, main="Control of institution", xlab="CONTROL")
hist(data$REGION, main="Regional location of institution", xlab="REGION")
hist(data$HBCU, main="Historically Black College and University", xlab="HBCU")

par(mfrow=c(1,5))
hist(data$PBI, main="Predominantly Black University", xlab="PBI")
hist(data$TRIBAL, main="Tribal college and university", xlab="TRIBAL")
hist(data$HSI, main="Hispanic-serving institution", xlab="HSI")
hist(data$WOMENONLY, main="Women-only College", xlab="WOMENONLY")
hist(data$COSTT4_A, main="Average cost of attendance per academic year", xlab="COSTT4_A")

par(mfrow=c(1,5))
hist(data$AVGFACSAL, main="Average faculty salary", xlab="AVGFACSAL")
hist(data$PFTFAC, main="Proportion of full-time faculty members", xlab="PFTFAC")
hist(data$PCTPELL, main="Percentage of undergraduates receiving Pell grant (financial aid)", xlab="PCTPELL")
hist(data$UG25ABV, main="Percentage of undergraduates aged 25 and above", xlab="UG25ABV")
hist(data$INC_PCT_LO, main="Percentage of aided students whose family income is between $0-$30,000", xlab="INC_PCT_LO")

par(mfrow=c(1,5))
hist(data$PAR_ED_PCT_1STGEN, main="Percentage of first-generation students", xlab="PAR_ED_PCT_1STGEN")
hist(data$FEMALE, main="Proportion of student body that is female", xlab="FEMALE")
hist(data$MD_FAMINC, main="Median family income of students", xlab="MD_FAMINC")
hist(data$PCT_WHITE, main="Percent of the population from students' zip codes that is White, via Census data", xlab="PCT_WHITE")
hist(data$PCT_BLACK, main="Percent of the population from students' zip codes that is Black, via Census data", xlab="PCT_BLACK")

par(mfrow=c(1,5))
hist(data$PCT_ASIAN, main="Percent of the population from students' zip codes that is Asian, via Census data", xlab="PCT_ASIAN")
hist(data$PCT_HISPANIC, main="Percent of the population from students' zip codes that is Hispanic, via Census data", xlab="PCT_HISPANIC")
hist(data$PCT_BA, main="Percent of the population from students' zip codes with a bachelor's degree over the age 25, via Census data", xlab="PCT_BA")
hist(data$PCT_GRAD_PROF, main="Percent of the population from students' zip codes over 25 with a professional degree, via Census data", xlab="PCT_GRAD_PROF")
hist(data$PCT_BORN_US, main="Percent of the population from students' zip codes that was born in the US, via Census data", xlab="PCT_BORN_US")

par(mfrow=c(1,5))
hist(data$POVERTY_RATE, main="Poverty rate, via Census data", xlab="POVERTY_RATE")
hist(data$UNEMP_RATE, main="Unemployment rate, via Census data", xlab="UNEMP_RATE")

plot(data$ADM_RATE ~ data$NUMBRANCH, main="Admission Rate vs. Number of branch campuses.", xlab="NUMBRANCH.", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$CONTROL, main="Admission Rate vs. Control of institution", xlab="CONTROL", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$REGION, main="Admission Rate vs. Region", xlab="REGION", ylab="ADM_RATE")

plot(data$ADM_RATE ~ data$HBCU, main="Admission Rate vs. HBCU", xlab="HBCU", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PBI, main="Admission Rate vs. PBI", xlab="PBI", ylab="ADM_RATE")

plot(data$ADM_RATE ~ data$TRIBAL, main="Admission Rate vs. TRIBAL", xlab="TRIBAL", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$HSI, main="Admission Rate vs. HSI.", xlab="HSI", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$WOMENONLY, main="Admission Rate vs. WOMENONLY", xlab="WOMENONLY", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$COSTT4_A, main="Admission Rate vs. COSTT4_A", xlab="COSTT4_A", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$AVGFACSAL, main="Admission Rate vs. AVGFACSAL", xlab="AVGFACSAL", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PFTFAC, main="Admission Rate vs. PFTFAC", xlab="PFTFAC", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCTPELL, main="Admission Rate vs. PCTPELL", xlab="PCTPELL", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$UG25ABV, main="Admission Rate vs. UG25ABV", xlab="UG25ABV", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$INC_PCT_LO, main="Admission Rate vs. INC_PCT_LO", xlab="INC_PCT_LO", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PAR_ED_PCT_1STGEN, main="Admission Rate vs. PAR_ED_PCT_1STGEN", xlab="PAR_ED_PCT_1STGEN", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$FEMALE, main="Admission Rate vs.FEMALE", xlab="FEMALE", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$MD_FAMINC, main="Admission Rate vs. MD_FAMINC", xlab="MD_FAMINC", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_WHITE, main="Admission Rate vs. PCT_WHITE", xlab="PCT_WHITE", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_BLACK, main="Admission Rate vs. PCT_BLACK", xlab="PCT_BLACK", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_ASIAN, main="Admission Rate vs. PCT_ASIAN", xlab="PCT_ASIAN", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_HISPANIC, main="Admission Rate vs. PCT_HISPANIC", xlab="PCT_HISPANIC", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_BA, main="Admission Rate vs. PCT_BA", xlab="PCT_BA", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_GRAD_PROF, main="Admission Rate vs. PCT_GRAD_PROF", xlab="PCT_GRAD_PROF", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$PCT_BORN_US, main="Admission Rate vs. PCT_BORN_US", xlab="PCT_BORN_US", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$POVERTY_RATE, main="Admission Rate vs. POVERTY_RATE", xlab="POVERTY_RATE", ylab="ADM_RATE")
plot(data$ADM_RATE ~ data$UNEMP_RATE, main="Admission Rate vs. UNEMP_RATE", xlab="UNEMP_RATE")
```
pbi- left or right (way more left) 


adm_rate- skewed to the right but theres a bell shape
numbranch- not symmetrical, no bell shape, skewed to left
control - 1, or 2, or 3 (bell shaped ig more skewed to left) 
region- no bell shape, not symmetrical, random 
hbcu- left or right (way more left) 

```{r}
mod1 <- lm(ADM_RATE ~ NUMBRANCH+CONTROL+REGION+HBCU+PBI, data=data)
mod2 <- lm(ADM_RATE ~ TRIBAL+HSI+WOMENONLY+COSTT4_A+AVGFACSAL, data=data)
mod3 <- lm(ADM_RATE ~ PFTFAC+PCTPELL+UG25ABV+INC_PCT_LO+PAR_ED_PCT_1STGEN, data=data)
mod4 <- lm(ADM_RATE ~ FEMALE+MD_FAMINC+PCT_WHITE+PCT_BLACK+PCT_ASIAN, data=data)
mod5 <- lm(ADM_RATE ~ PCT_HISPANIC+PCT_BA+PCT_GRAD_PROF+PCT_BORN_US+POVERTY_RATE+UNEMP_RATE, data=data)
r1 <- resid(mod1) 
r2 <- resid(mod2) 
r3 <- resid(mod3) 
r4 <- resid(mod4) 
r5 <- resid(mod5) 
# first check condition 1 and 2
# later we will know any pattern we see is tied to a problem when looking at the residual plots - actually violations of assumptions or something else
pairs(data[,2:6], main='Pairwise Plot 1') #take a set of data (the predictors) and make all possible pairwise plots of them
# scatterplot, second tab plot
plot(data$ADM_RATE ~ fitted(mod1), main="Residual v. Fitted of Mod1", xlab="Y-hat", ylab="Y") #fitted values from x 
abline(a = 0, b = 1) # <- this is a straight diagonal line which represents identity function with slope of 1 and intercept of 0
lines(lowess(data$ADM_RATE ~ fitted(mod1)), lty=2) # lowess() fits a smooth dotted line onto the plots so it would be easier to see if any data doesn't have linear relationship (straight lines)

pairs(data[,7:11], main = 'Pairwise Plot 2') 
plot(data$ADM_RATE ~ fitted(mod2), main="Residual v. Mod2", xlab="Y-hat2", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(data$ADM_RATE ~ fitted(mod2)), lty=2)

pairs(data[,12:16], main = 'Pairwise Plot 3') 
plot(data$ADM_RATE ~ fitted(mod3), main="Residual v. Mod3", xlab="Y-hat3", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(data$ADM_RATE ~ fitted(mod3)), lty=2)

pairs(data[,17:21], main = 'Pairwise Plot 4') 
plot(data$ADM_RATE ~ fitted(mod4), main="Residual v. Mod4", xlab="Y-hat4", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(data$ADM_RATE ~ fitted(mod4)), lty=2)

pairs(data[,22:27], main = 'Pairwise Plot 5') 
plot(data$ADM_RATE ~ fitted(mod5), main="Residual v. Fitted of Mod5", xlab="Y-hat5", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(data$ADM_RATE ~ fitted(mod5)), lty=2)

par(mfrow=c(2,3))
plot(r1 ~ fitted(mod1), main='Fitted v. Residual for mod1', xlab='Fitted', ylab='res.')
plot(r1 ~ data$NUMBRANCH, main='Fitted v. Residual for NUMBRANCH', xlab='Number of Branch', ylab='res')
plot(r1 ~ data$CONTROL, main='Fitted v. Residual', xlab='control', ylab='res')
plot(r1 ~ data$REGION, main='Fitted v. Residual', xlab='Region', ylab='res')
plot(r1 ~ data$HBCU, main='Fitted v. Residual', xlab='hbcu', ylab='res')
plot(r1 ~ data$PBI, main='Fitted v. Residual', xlab='pbi', ylab='res')

par(mfrow=c(2,3))
plot(r2 ~ fitted(mod2), main='Fitted v. Residual for mod2', xlab='Fitted', ylab='res.')
plot(r2 ~ data$TRIBAL, main='Fitted v. Residual', xlab='TRIBAL', ylab='res')
plot(r2 ~ data$HSI, main='Fitted v. Residual', xlab='HSI', ylab='res')
plot(r2 ~ data$WOMENONLY, main='Fitted v. Residual', xlab='WOMENONLY', ylab='res')
plot(r2 ~ data$COSTT4_A, main='Fitted v. Residual', xlab='COSTT4_A', ylab='res')
plot(r2 ~ data$AVGFACSAL, main='Fitted v. Residual', xlab='AVGFASCAL', ylab='res')

par(mfrow=c(2,3))
plot(r3 ~ fitted(mod3), main='Fitted v. Residual for mod3', xlab='Fitted', ylab='res.')
plot(r3 ~ data$PFTFAC, main='Fitted v. Residual', xlab='PFTFAC', ylab='res')
plot(r3 ~ data$PCTPELL, main='Fitted v. Residual', xlab='PCTPELL', ylab='res')
plot(r3 ~ data$UG25ABV, main='Fitted v. Residual', xlab='UG25ABV', ylab='res')
plot(r3 ~ data$INC_PCT_LO, main='Fitted v. Residual', xlab='INC_PCT_LO', ylab='res')
plot(r3 ~ data$PAR_ED_PCT_1STGEN, main='Fitted v. Residual', xlab='PAR_ED_PCT_1STGEN', ylab='res')

par(mfrow=c(2,3))
plot(r4 ~ fitted(mod4), main='Fitted v. Residual for mod4', xlab='Fitted', ylab='res.')
plot(r4 ~ data$FEMALE, main='Fitted v. Residual', xlab='FEMALE', ylab='res')
plot(r4 ~ data$MD_FAMINC, main='Fitted v. Residual', xlab='MD_FAMINC', ylab='res')
plot(r4 ~ data$PCT_WHITE, main='Fitted v. Residual', xlab='PCT_WHITE', ylab='res')
plot(r4 ~ data$PCT_BLACK, main='Fitted v. Residual', xlab='PCT_BLACK', ylab='res')
plot(r4 ~ data$PCT_ASIAN, main='Fitted v. Residual', xlab='PCT_ASIAN', ylab='res')

par(mfrow=c(2,3))
plot(r5 ~ fitted(mod5), main='Fitted v. Residual for mod5', xlab='Fitted', ylab='res.')
plot(r5 ~ data$PCT_HISPANIC, main='Fitted v. Residual', xlab='PCT_HISPANIC', ylab='res')
plot(r5 ~ data$PCT_BA, main='Fitted v. Residual', xlab='PCT_BA', ylab='res')
plot(r5 ~ data$PCT_GRAD_PROF, main='Fitted v. Residual', xlab='PCT_GRAD_PROF', ylab='res')
plot(r5 ~ data$PCT_BORN_US, main='Fitted v. Residual', xlab='PCT_BORN_US', ylab='res')
plot(r5 ~ data$POVERTY_RATE, main='Fitted v. Residual', xlab='POVERTY_RATE', ylab='res')
#QQ plot function
qqnorm(r1)
qqline(r1)

qqnorm(r2)
qqline(r2)

qqnorm(r3)
qqline(r3)

qqnorm(r4)
qqline(r4)

qqnorm(r5)
qqline(r5)
```
```{r}
qqnorm(r3)
qqline(r3)
```

```{r}
install.packages("car")
library(car)

# first Box-Cox on Y
boxCox(mod1,family="bcnPower")
boxCox(mod2,family="bcnPower")
boxCox(mod3,family="bcnPower")
boxCox(mod4,family="bcnPower")
boxCox(mod5,family="bcnPower")

transdata <- data %>% 
  mutate(newNUMBRANCH = NUMBRANCH + 0.5,newCONTROL = CONTROL + 0.5,newREGION = REGION + 0.5,newHBCU = HBCU + 0.5, newPBI = PBI + 0.5, newTRIBAL = TRIBAL + 0.5, newHSI = HSI + 0.5, newWOMENONLY = WOMENONLY + 0.5,newADM_RATE = ADM_RATE + 0.5, newCOSTT4_A = COSTT4_A + 0.5,newAVGFACSAL = AVGFACSAL + 0.5,newPFTFAC = PFTFAC + 0.5,newPCTPELL = PCTPELL + 0.5,newUG25ABV = UG25ABV + 0.5,newINC_PCT_LO = INC_PCT_LO + 0.5,newPAR_ED_PCT_1STGEN = PAR_ED_PCT_1STGEN + 0.5,newFEMALE = FEMALE + 0.5,newMD_FAMINC = MD_FAMINC + 0.5,newPCT_WHITE = PCT_WHITE + 0.5,newPCT_BLACK = PCT_BLACK + 0.5,newPCT_ASIAN = PCT_ASIAN + 0.5,newPCT_HISPANIC = PCT_HISPANIC + 0.5,newPCT_BA = PCT_BA + 0.5,newPCT_GRAD_PROF = PCT_GRAD_PROF + 0.5,newPCT_BORN_US = PCT_BORN_US + 0.5,newPOVERTY_RATE = POVERTY_RATE + 0.5,newUNEMP_RATE = UNEMP_RATE + 0.5)

transdata <- transdata %>%
  select(newADM_RATE, newNUMBRANCH, newCONTROL, newREGION, newHBCU, newPBI, newTRIBAL, newHSI, newWOMENONLY, newCOSTT4_A, newAVGFACSAL, newPFTFAC, newPCTPELL, newUG25ABV, newINC_PCT_LO, newPAR_ED_PCT_1STGEN, newFEMALE, newMD_FAMINC, newPCT_WHITE, newPCT_BLACK, newPCT_ASIAN, newPCT_HISPANIC, newPCT_BA, newPCT_GRAD_PROF, newPCT_BORN_US, newPOVERTY_RATE, newUNEMP_RATE)

```

```{r} 
#eda with transformations
newmod1 <- lm(I(sqrt(newADM_RATE)) ~ newNUMBRANCH+newCONTROL+newREGION+newHBCU+newPBI, data=transdata)
newmod2 <- lm(I(sqrt(newADM_RATE)) ~ newTRIBAL+newHSI+newWOMENONLY+newCOSTT4_A+newAVGFACSAL, data=transdata)
newmod3 <- lm(I(sqrt(newADM_RATE)) ~ newPFTFAC+newPCTPELL+newUG25ABV+newINC_PCT_LO+newPAR_ED_PCT_1STGEN, data=transdata)
newmod4 <- lm(I(sqrt(newADM_RATE)) ~ newFEMALE+newMD_FAMINC+newPCT_WHITE+newPCT_BLACK+newPCT_ASIAN, data=transdata)
newmod5 <- lm(I(sqrt(newADM_RATE)) ~ newPCT_HISPANIC+newPCT_BA+newPCT_GRAD_PROF+newPCT_BORN_US+newPOVERTY_RATE+newUNEMP_RATE, data=transdata)
newr1 <- resid(newmod1) 
newr2 <- resid(newmod2) 
newr3 <- resid(newmod3) 
newr4 <- resid(newmod4) 
newr5 <- resid(newmod5) 
# first check condition 1 and 2
# later we will know any pattern we see is tied to a problem when looking at the residual plots - actually violations of assumptions or something else
pairs(transdata[,2:6], main='Pairwise Plot 1') #take a set of data (the predictors) and make all possible pairwise plots of them
# scatterplot, second tab plot
plot(transdata$newADM_RATE ~ fitted(newmod1), main="Residual v. Fitted of Mod1", xlab="Y-hat", ylab="Y") #fitted values from x 
abline(a = 0, b = 1) # <- this is a straight diagonal line which represents identity function with slope of 1 and intercept of 0
lines(lowess(transdata$newADM_RATE ~ fitted(newmod1)), lty=2) # lowess() fits a smooth dotted line onto the plots so it would be easier to see if any data doesn't have linear relationship (straight lines)

pairs(transdata[,7:11], main = 'Pairwise Plot 2') 
plot(transdata$newADM_RATE ~ fitted(newmod2), main="Residual v. Mod2", xlab="Y-hat2", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(transdata$newADM_RATE ~ fitted(newmod2)), lty=2)

pairs(transdata[,12:16], main = 'Pairwise Plot 3') 
plot(transdata$newADM_RATE ~ fitted(newmod3), main="Residual v. Mod3", xlab="Y-hat3", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(transdata$newADM_RATE ~ fitted(newmod3)), lty=2)

pairs(transdata[,17:21], main = 'Pairwise Plot 4') 
plot(transdata$newADM_RATE ~ fitted(newmod4), main="Residual v. Mod4", xlab="Y-hat4", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(transdata$newADM_RATE ~ fitted(newmod4)), lty=2)

pairs(transdata[,22:27], main = 'Pairwise Plot 5') 
plot(transdata$newADM_RATE ~ fitted(newmod5), main="Residual v. Fitted of Mod5", xlab="Y-hat5", ylab="Y") 
abline(a = 0, b = 1) 
lines(lowess(transdata$newADM_RATE ~ fitted(newmod5)), lty=2)

qqnorm(newr1, main = 'mod1' )

qqnorm(newr2, main = 'mod2')

qqnorm(newr3, main = 'mod3')

qqnorm(newr4, main = 'mod4')

qqnorm(newr5, main = 'mod5')


``` 

```{r }
student_char_data <- data %>% select(ADM_RATE, PCTPELL, UG25ABV, INC_PCT_LO, PAR_ED_PCT_1STGEN, FEMALE, MD_FAMINC, PCT_WHITE, PCT_BLACK, PCT_ASIAN, PCT_HISPANIC, PCT_BA, PCT_GRAD_PROF, PCT_BORN_US, POVERTY_RATE, UNEMP_RATE)

#STUDENT CHARACTERISTICS
mod_student_char <-lm(ADM_RATE~ + PCTPELL + UG25ABV + INC_PCT_LO + PAR_ED_PCT_1STGEN + FEMALE + MD_FAMINC + PCT_WHITE + PCT_BLACK + PCT_ASIAN + PCT_HISPANIC + PCT_BA + PCT_GRAD_PROF + PCT_BORN_US + POVERTY_RATE + UNEMP_RATE, data=student_char_data)
summary(mod_student_char)

#decomposition 

#finding SST
var(student_char_data$ADM_RATE)*(nrow(student_char_data)-1)
SST <- sum((student_char_data$ADM_RATE - mean(student_char_data$ADM_RATE))^2)

#finding RSS
RSS <-summary(mod_student_char)$sigma^2*(nrow(student_char_data)- length(coef(mod_student_char)))
sum((student_char_data$ADM_RATE- fitted(mod_student_char))^2)

##SSreg
SSreg <- SST-RSS
sum((fitted(mod_student_char)- mean(student_char_data$ADM_RATE))^2)

#adjusted R^2
R2_adj <- 1 - ((RSS/(nrow(student_char_data)-15-1))/(SST/(nrow(student_char_data)-1)))
R2_adj
```


```{r}
school_char_data <- data %>% select(ADM_RATE, COSTT4_A, AVGFACSAL, PFTFAC)

#SCHOOL CHARACTERISTICS
mod_school_char <-lm(ADM_RATE~ + COSTT4_A + AVGFACSAL + PFTFAC, data=school_char_data)
summary(mod_school_char)

#decomposition 

#finding SST
var(school_char_data$ADM_RATE)*(nrow(school_char_data)-1)
SST <- sum((school_char_data$ADM_RATE - mean(school_char_data$ADM_RATE))^2)

#finding RSS
RSS <-summary(mod_school_char)$sigma^2*(nrow(school_char_data)- length(coef(mod_school_char)))
sum((school_char_data$ADM_RATE- fitted(mod_school_char))^2)

##SSreg
SSreg <- SST-RSS
sum((fitted(mod_school_char)- mean(school_char_data$ADM_RATE))^2)

#adjusted R^2
R2_adj <- 1 - ((RSS/(nrow(school_char_data)-3-1))/(SST/(nrow(school_char_data)-1)))
R2_adj
```
```{r}
school_ident_data <- data %>% select(ADM_RATE, NUMBRANCH, CONTROL, REGION, HBCU, PBI, TRIBAL, HSI, WOMENONLY)

#SCHOOL IDENTIFICATION
mod_school_ident <-lm(ADM_RATE~ NUMBRANCH + CONTROL + REGION + HBCU + PBI + TRIBAL + HSI + WOMENONLY, data=school_ident_data)
summary(mod_school_ident)

#decomposition 

#finding SST
var(school_ident_data$ADM_RATE)*(nrow(school_ident_data)-1)
SST <- sum((school_ident_data$ADM_RATE - mean(school_ident_data$ADM_RATE))^2)

#finding RSS
RSS <-summary(mod_school_ident)$sigma^2*(nrow(school_ident_data)- length(coef(mod_school_ident)))
sum((school_ident_data$ADM_RATE- fitted(mod_school_ident))^2)

##SSreg
SSreg <- SST-RSS
sum((fitted(mod_school_ident)- mean(school_ident_data$ADM_RATE))^2)

#adjusted R^2
R2_adj <- 1 - ((RSS/(nrow(school_ident_data)-8-1))/(SST/(nrow(school_ident_data)-1)))
R2_adj
```
r2adj_student_char= 0.1406
r2adj_school_char = 0.1464
r2adj_school_ident = 0.02622

```{r} 
#partial f test 

#original vs when we take out school identitfiers
mod_original <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newHBCU + newPBI + newTRIBAL + newHSI + newWOMENONLY, data=transdata)

mod_wo_sch_ident <-lm(newADM_RATE~ + newPCTPELL +  newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC, data=transdata)

mod_wo_sch_char <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE +  newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newNUMBRANCH + newCONTROL + newREGION + newHBCU + newPBI + newTRIBAL + newHSI + newWOMENONLY, data=transdata)

mod_wo_stu_char<-lm(newADM_RATE~ newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newHBCU + newPBI + newTRIBAL + newHSI + newWOMENONLY, data=transdata)


summary(mod_original)
summary(mod_wo_sch_ident)
summary(mod_wo_sch_char)
summary(mod_wo_stu_char)


#partial f calc
#rss full vs rss drop

RSSfull <-summary(mod_original)$sigma^2*(nrow(transdata)- length(coef(mod_original)))
sum((transdata$newADM_RATE- fitted(mod_original))^2)

RSSdrop_sch_ident <-summary(mod_wo_sch_ident)$sigma^2*(nrow(transdata)- length(coef(mod_wo_sch_ident)))
sum((transdata$newADM_RATE- fitted(mod_wo_sch_ident))^2)

RSSdrop_sch_char <-summary(mod_wo_sch_char)$sigma^2*(nrow(transdata)- length(coef(mod_wo_sch_char)))
sum((transdata$newADM_RATE- fitted(mod_wo_sch_char))^2)

RSSdrop_stu_char <-summary(mod_wo_stu_char)$sigma^2*(nrow(transdata)- length(coef(mod_wo_stu_char)))
sum((transdata$newADM_RATE- fitted(mod_wo_stu_char))^2)


partial_f_wo_sch_ident <- (RSSdrop_sch_ident/8)/(RSSfull/(1508-26-1))

partial_f_wo_sch_char <- (RSSdrop_sch_char/3)/(RSSfull/(1508-26-1))

partial_f_wo_stu_char <- (RSSdrop_stu_char/15)/(RSSfull/(1508-26-1))


partial_f_wo_sch_ident

partial_f_wo_sch_char

partial_f_wo_stu_char
```
```{r}
mod_wo_x <-lm(newADM_RATE~ newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION, data=transdata)

summary(mod_wo_x)

mod_wo_y <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newHBCU + newPBI + newTRIBAL + newHSI + newWOMENONLY, data=transdata)

summary(mod_wo_y)

mod_wo_a <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newHBCU + newPBI, data=transdata)

summary(mod_wo_a)

mod_original <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newHBCU + newPBI + newTRIBAL + newHSI + newWOMENONLY, data=transdata)

mod_wo_b <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newTRIBAL + newHSI + newWOMENONLY, data=transdata)

mod_wo_c <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newPBI + newWOMENONLY, data=transdata)

mod_wo_d <-lm(newADM_RATE~ + newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE + newPCT_BLACK + newPCT_ASIAN + newPCT_HISPANIC + newPCT_BA + newPCT_GRAD_PROF + newPCT_BORN_US + newPOVERTY_RATE + newUNEMP_RATE + newCOSTT4_A + newAVGFACSAL + newPFTFAC + newNUMBRANCH + newCONTROL + newREGION + newHBCU+ newTRIBAL + newHSI, data=transdata)
# let x be subset of predicotrs we assume that are not important hbcu, pbi, tribal, hsi, womenonly

#let y be num branch and control and region

#let a be tribal and hsi and women only
#b is hbcu and pbi 
#c is hbcu tribal and hsi
#d is pbi and womenonly


#partial f calc
#rss full vs rss drop

RSSfull <-summary(mod_original)$sigma^2*(nrow(transdata)- length(coef(mod_original)))
sum((transdata$newADM_RATE- fitted(mod_original))^2)

RSSdrop_x <-summary(mod_wo_x)$sigma^2*(nrow(transdata)- length(coef(mod_wo_x)))
sum((transdata$newADM_RATE- fitted(mod_wo_x))^2)

RSSdrop_y <-summary(mod_wo_y)$sigma^2*(nrow(transdata)- length(coef(mod_wo_y)))
sum((transdata$newADM_RATE- fitted(mod_wo_y))^2)

RSSdrop_a <-summary(mod_wo_a)$sigma^2*(nrow(transdata)- length(coef(mod_wo_a)))
sum((transdata$newADM_RATE- fitted(mod_wo_a))^2)

RSSdrop_b <-summary(mod_wo_b)$sigma^2*(nrow(transdata)- length(coef(mod_wo_b)))
sum((transdata$newADM_RATE- fitted(mod_wo_b))^2)

RSSdrop_c <-summary(mod_wo_c)$sigma^2*(nrow(transdata)- length(coef(mod_wo_c)))
sum((transdata$newADM_RATE- fitted(mod_wo_c))^2)

RSSdrop_d <-summary(mod_wo_d)$sigma^2*(nrow(transdata)- length(coef(mod_wo_d)))
sum((transdata$newADM_RATE- fitted(mod_wo_d))^2)

partial_f_wo_x <- (RSSdrop_x/5)/(RSSfull/(1508-26-1))

partial_f_wo_y <- (RSSdrop_y/3)/(RSSfull/(1508-26-1))

partial_f_wo_a <- (RSSdrop_a/3)/(RSSfull/(1508-26-1))

partial_f_wo_b <- (RSSdrop_b/2)/(RSSfull/(1508-26-1))

partial_f_wo_c <- (RSSdrop_c/2)/(RSSfull/(1508-26-1))

partial_f_wo_d <- (RSSdrop_d/2)/(RSSfull/(1508-26-1))

partial_f_wo_x
partial_f_wo_y
partial_f_wo_a
partial_f_wo_b
partial_f_wo_c
partial_f_wo_d
```

```{r}
school_char_data <- transdata %>% select(newADM_RATE, newCOSTT4_A, newAVGFACSAL, newPFTFAC)
stuchar_data <- transdata %>% select(newADM_RATE, newPCTPELL, newUG25ABV, newINC_PCT_LO, newPAR_ED_PCT_1STGEN , newFEMALE, newMD_FAMINC, newPCT_WHITE, newPCT_BLACK, newPCT_ASIAN, newPCT_HISPANIC, newPCT_BA, newPCT_GRAD_PROF , newPCT_BORN_US, newPOVERTY_RATE, newUNEMP_RATE) 

stusch_char <- bind_cols(stuchar_data, school_char_data)

view(stusch_char)
summary(stusch_char)

school_char_data <- transdata %>% select(newADM_RATE, newCOSTT4_A, newAVGFACSAL, newPFTFAC)
stuchar_data <- transdata %>% select(newADM_RATE, newPCTPELL, newUG25ABV, newINC_PCT_LO, newPAR_ED_PCT_1STGEN , newFEMALE, newMD_FAMINC, newPCT_WHITE, newPCT_BLACK, newPCT_ASIAN, newPCT_HISPANIC, newPCT_BA, newPCT_GRAD_PROF , newPCT_BORN_US, newPOVERTY_RATE, newUNEMP_RATE) 

stusch_char <- bind_cols(stuchar_data, school_char_data)

view(stusch_char)
summary(stusch_char)
stusch_char = select(stusch_char, -17) 
stusch_char <- stusch_char %>% rename(newADM_RATE = newADM_RATE...1)

testmodel <- lm(newADM_RATE ~ newPCTPELL + newUG25ABV + newINC_PCT_LO + newPAR_ED_PCT_1STGEN + newFEMALE + newMD_FAMINC + newPCT_WHITE+ newPCT_BLACK+ newPCT_ASIAN+ newPCT_HISPANIC+ newPCT_BA+ newPCT_GRAD_PROF+ newPCT_BORN_US+ newPOVERTY_RATE+ newUNEMP_RATE + newCOSTT4_A+ newAVGFACSAL+ newPFTFAC, data = stusch_char)
summary(testmodel)
summary(testmodel)$coefficients

confint(testmodel, level = 0.95)
```

